# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

symmCpp <- function(X, d) {
    .Call('_BET_symmCpp', PACKAGE = 'BET', X, d)
}

BETCpp <- function(X, d) {
    .Call('_BET_BETCpp', PACKAGE = 'BET', X, d)
}

