# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

symmCpp <- function(X_R, d, unif) {
    .Call('_BET_symmCpp', PACKAGE = 'BET', X_R, d, unif)
}

colorCpp <- function(X_R, d, unif) {
    .Call('_BET_colorCpp', PACKAGE = 'BET', X_R, d, unif)
}

cellCpp <- function(X_R, d, unif) {
    .Call('_BET_cellCpp', PACKAGE = 'BET', X_R, d, unif)
}

BETCpp <- function(X_R, d, unif, asymptotic, test_uniformity, test_independence, independence_index) {
    .Call('_BET_BETCpp', PACKAGE = 'BET', X_R, d, unif, asymptotic, test_uniformity, test_independence, independence_index)
}

BeastCpp <- function(X_R, d, m, B, unif, lambda, test_uniformity, test_independence, independence_index, method, numPerm) {
    .Call('_BET_BeastCpp', PACKAGE = 'BET', X_R, d, m, B, unif, lambda, test_uniformity, test_independence, independence_index, method, numPerm)
}

